@extends('client.inside.layout')
@section('content')
<div class="col-sm-9 col-xs-12 nav-tabs-right">
                <div class="title-left margin-five-top-768">HƯỚNG DẪN NẠP BẰNG ZALO PAY</div>
				<div style="display:block;text-align:center;margin-right:auto;margin-left:auto">
	&nbsp;</div>
<p>
	<span><span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap">Quý bằng hữu thân mến,</span></span></p>
<div>
	<br>
	<p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:8pt;text-align:justify">
		<span style="background-color:transparent;font-size:12pt;font-family:Tahoma;color:rgb(153,0,0);font-weight:700;vertical-align:baseline;white-space:pre-wrap">Thiên Long Tình Kiếm</span><span style="background-color:transparent;font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);vertical-align:baseline;white-space:pre-wrap"> trân trọng thông báo bắt đầu từ </span><span style="background-color:transparent;font-size:12pt;font-family:Tahoma;color:rgb(153,0,0);vertical-align:baseline;white-space:pre-wrap">14h00</span><span style="background-color:transparent;font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);vertical-align:baseline;white-space:pre-wrap"> ngày</span><span style="background-color:transparent;font-size:12pt;font-family:Tahoma;color:rgb(153,0,0);vertical-align:baseline;white-space:pre-wrap"> 27/04/2018 </span><span style="background-color:transparent;font-size:12pt;font-family:Tahoma;color:rgb(153,0,0);font-weight:700;vertical-align:baseline;white-space:pre-wrap">Thiên Long Tình Kiếm</span><span style="background-color:transparent;font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);vertical-align:baseline;white-space:pre-wrap"> hỗ trợ nạp thẻ qua kênh thanh toán mới </span><span style="background-color:transparent;font-size:12pt;font-family:Tahoma;color:rgb(0,0,255);vertical-align:baseline;white-space:pre-wrap">ZaloPay</span><span style="background-color:transparent;font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);vertical-align:baseline;white-space:pre-wrap">. Việc tích hợp này sẽ thêm một phương thức nạp đồng mới, nhanh, dễ dàng và tiện lợi hơn. </span></p>
	<p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:8pt;text-align:justify">
		<span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap"><span><span style="font-size:12pt;background-color:transparent;font-weight:700;vertical-align:baseline">Đặc biệt: </span><span style="font-size:12pt;background-color:transparent;vertical-align:baseline">khi nạp thẻ qua </span><span style="font-size:12pt;color:rgb(0,0,255);background-color:transparent;vertical-align:baseline">ZaloPay</span><span style="font-size:12pt;background-color:transparent;vertical-align:baseline">, bằng hữu được hưởng thêm </span><span style="font-size:12pt;background-color:transparent;font-weight:700;vertical-align:baseline">9%</span><span style="font-size:12pt;background-color:transparent;vertical-align:baseline"> giá trị nạp.</span></span></span></p>
	<p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:8pt;text-align:justify">
		<img src="https://www.upsieutoc.com/images/2020/09/02/QRcode3.png" style="background-color: transparent; color: rgb(0, 0, 0); font-family: Tahoma; font-size: 12pt; white-space: pre-wrap; border: none; transform: rotate(0rad); width: 650px; height: 379px;"></p>
	<div style="display:block;text-align:left">
		&nbsp;</div>
	<div style="text-align: center;">
		<span id="docs-internal-guid-d04de910-7fff-787b-69cd-9e9b68f65370"><img src="https://www.upsieutoc.com/images/2020/09/02/as.png" style="background-color: transparent; color: rgb(0, 0, 0); font-family: Tahoma; font-size: 12pt; white-space: pre-wrap; border: none; transform: rotate(0rad); width: 650px; height: 272px;"></span></div>
	<p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:8pt;text-align:center">
		<span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;font-style:italic;vertical-align:baseline;white-space:pre-wrap">QR CODE Thiên Long Tình Kiếm</span></p>
	<p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:8pt;text-align:justify">
		<span style="background-color:transparent;font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);vertical-align:baseline;white-space:pre-wrap"><span style="background-color:transparent;font-size:12pt">Để các bằng hữu không khỏi bỡ ngỡ khi thực hiện các thao tác BQT xin hướng dẫn các bước nạp đồng qua kênh thanh toán mới </span></span><span style="background-color:transparent;color:rgb(0,0,255);font-family:Tahoma;font-size:16px;white-space:pre-wrap">ZaloPay </span><span style="background-color:transparent;color:rgb(0,0,0);font-family:Tahoma;font-size:16px;white-space:pre-wrap">như sau:</span></p>
	<p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:8pt;text-align:justify">
		<span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;font-weight:700;vertical-align:baseline;white-space:pre-wrap">5 BƯỚC NẠP ĐỒNG QUA ZALOPAY:</span></p>
	<p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:8pt;text-align:justify">
		<span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;font-weight:700;vertical-align:baseline;white-space:pre-wrap">BƯỚC 1:</span><span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap"> Cài đặt ứng dụng ZaloPay trên nền tảng iOS &amp; Android: </span></p>
	<p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:0pt;text-align:justify">
		<span><span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap">Mở chợ ứng dụng </span><a href="https://play.google.com/store/apps/details?id=vn.com.vng.zalopay"><span style="font-size:12pt;font-family:Tahoma;color:rgb(17,85,204);background-color:transparent;vertical-align:baseline;white-space:pre-wrap">(Google Play</span></a><span style="font-size:12pt;font-family:Tahoma;color:rgb(255,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap"> </span><span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap">đối với Android và </span><a href="https://itunes.apple.com/us/app/zalo-pay-thanh-toan-trong/id1112407590?mt=8"><span style="font-size:12pt;font-family:Tahoma;color:rgb(17,85,204);background-color:transparent;vertical-align:baseline;white-space:pre-wrap">Apple Store</span></a><span style="font-size:12pt;font-family:Tahoma;color:rgb(255,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap"> </span><span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap">đối với iOS), bạn nhập từ tìm kiếm:</span><span style="font-size:12pt;font-family:Tahoma;color:rgb(255,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap"> </span><span style="font-size:12pt;font-family:Tahoma;color:rgb(153,0,0);background-color:transparent;font-weight:700;vertical-align:baseline;white-space:pre-wrap">ZaloPay </span><span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap">để tiến hành cài đặt.</span></span></p>
	<div style="display:block;text-align:center;margin-right:auto;margin-left:auto">
		<img height="267" src="https://lh4.googleusercontent.com/m1jSM86p3N7iO_buq8KLM3R_ZyKCWbvELIFskur3Bvcjz0GDUhErFaOr_oafEe_AG6Ve7YifPyGTHAk8rM-0ib9aVEDMV6gmiAm4OhamoFok0louNgN_MMZ0EGE9CdIDY3tq1p0Vij4d9ZV8ZQ" style="background-color: transparent; color: rgb(0, 0, 0); font-family: Tahoma; font-size: 11pt; white-space: pre-wrap; border: none; transform: rotate(0rad);" width="343"></div>
	<br>
	<p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:0pt;text-align:center;padding:0pt 0pt 0pt 36pt">
		<span><span style="font-size:11pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;font-style:italic;vertical-align:baseline;white-space:pre-wrap">Download Zalo Pay trên Android </span><span style="font-size:11pt;font-family:Tahoma;color:rgb(17,85,204);background-color:transparent;font-style:italic;vertical-align:baseline;white-space:pre-wrap"><a href="https://play.google.com/store/apps/details?id=vn.com.vng.zalopay">tại đây</a></span></span></p>
	<p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:0pt;text-align:center;padding:0pt 0pt 0pt 36pt">
		&nbsp;</p>
	<div style="display:block;text-align:center;margin-right:auto;margin-left:auto">
		<span id="docs-internal-guid-22f2f0fc-7fff-f0fa-baea-4c47d27bdac3"><span style="font-size: 11pt; font-family: Tahoma; color: rgb(0, 0, 0); background-color: transparent; font-style: italic; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;"><img height="330" src="https://lh4.googleusercontent.com/7oqu_XyRLSGuDBHkrC7pbV9NjtRd2XOHFf56z9eVdUqV6OafAkMqafWPgLEbuDjFGM_L_CRNemY1tmg37WVMWXY_omc9_TdTEK1HQe59qLA3TogKu-oE32sB90h6ZhcbXWvfUYPn" style="border: none; transform: rotate(0.00rad); -webkit-transform: rotate(0.00rad);" width="318"></span></span></div>
	<p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:0pt;text-align:center;padding:0pt 0pt 0pt 36pt">
		<span><span style="font-size:11pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;font-style:italic;vertical-align:baseline;white-space:pre-wrap">Download Zalo Pay trên iOS</span><a href="https://itunes.apple.com/us/app/zalo-pay-thanh-toan-trong/id1112407590?mt=8"><span style="font-size:11pt;font-family:Tahoma;color:rgb(17,85,204);background-color:transparent;font-style:italic;vertical-align:baseline;white-space:pre-wrap"> tại đây</span></a></span></p>
	<br>
	<p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:8pt;text-align:justify">
		<span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;font-weight:700;vertical-align:baseline;white-space:pre-wrap">BƯỚC 2:</span><span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap"> </span><span style="font-size:12pt;font-family:Tahoma;color:rgb(51,51,51);vertical-align:baseline;white-space:pre-wrap">Mở</span><span style="font-size:12pt;font-family:Tahoma;color:rgb(255,0,0);vertical-align:baseline;white-space:pre-wrap"> ZaloPay </span><span style="font-size:12pt;font-family:Tahoma;color:rgb(51,51,51);vertical-align:baseline;white-space:pre-wrap">và tạo tài khoản giao dịch lần lượt từng bước theo hướng dẫn. Đăng nhập vào sau khi có tài khoản, sau khi đăng nhập vào, bạn sẽ thấy giao diện dưới đây.</span></p>
	<div style="display:block;text-align:center;margin-right:auto;margin-left:auto">
		<span id="docs-internal-guid-b509b38c-7fff-18b2-edb4-41ebf4a39c22"><span style="font-size: 11pt; font-family: Tahoma; color: rgb(0, 0, 0); background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;"><img height="401" src="https://lh3.googleusercontent.com/7k5R1Ey4IsoxjbMF7Jy_8ceaK8XB9YbZVeuAVEHZqeaIGQ_uzLge0vwPVBiPd-7oM5fpKmPbZP-izK15xUqIcSARb0MrHbXy8AvcgnaPux5Usr5mERNEEEH1BxJMeEqQjiN8WQkn7O3Yi5GVDA" style="border: none; transform: rotate(0.00rad); -webkit-transform: rotate(0.00rad);" width="233"></span></span></div>
	<br>
	<p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:0pt;text-align:justify">
		<span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap">Nhấn vào chức năng liên kết ngân hàng, chọn Ngân Hàng và làm theo hướng dẫn từ ngân hàng tương ứng.</span></p>
	<p dir="ltr" style="line-height:1.8;margin-top:0pt;margin-bottom:0pt;text-align:justify">
		<span style="font-size:10pt;font-family:Tahoma;color:rgb(51,51,51);background-color:transparent;font-style:italic;vertical-align:baseline;white-space:pre-wrap">- Bạn có thể an tâm liên kết thẻ với ZaloPay vì toàn bộ hệ thống được bảo mật cao. </span></p>
	<p dir="ltr" style="line-height:1.8;margin-top:0pt;margin-bottom:0pt;text-align:justify">
		<span style="font-size:10pt;font-family:Tahoma;color:rgb(51,51,51);background-color:transparent;font-style:italic;vertical-align:baseline;white-space:pre-wrap">- Xác nhận mã OTP và thiết lập mật khẩu thanh toán 6 số bảo vệ. Phải xác nhận lại mật khẩu thanh toán cho mỗi lần thanh toán.</span></p>
	<p dir="ltr" style="line-height:1.8;margin-top:0pt;margin-bottom:9pt;text-align:justify">
		<span style="font-size:10pt;font-family:Tahoma;color:rgb(51,51,51);background-color:transparent;font-style:italic;vertical-align:baseline;white-space:pre-wrap">- Liên kết được nhiều thẻ khác nhau trên 1 tài khoản ZaloPay. Không cần điền lại thông tin thẻ cho những lần thanh toán sau. Có thể Xóa Thẻ bất cứ lúc nào bạn muốn.</span></p>
	<div style="display:block;text-align:center;margin-right:auto;margin-left:auto">
		<span id="docs-internal-guid-b70bf5e5-7fff-3cf3-0805-62e3ead3878d"><span style="font-size: 11pt; font-family: Tahoma; color: rgb(0, 0, 0); background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;"><img height="374" src="https://lh4.googleusercontent.com/6_NbOLfoZm6Fiwk77x5cqsNm_EtCzugjHJBNLtrC83NgzoKNFPV5Wv6j5p0bLBQz1_4xDjOdexlNy8W1CNrBKqTBJBLb4jJ9Qcd8zDEqX2u146BW8et7CsFa3eURfL6d3IIZnEU_OnEzugiUsw" style="border: none; transform: rotate(0.00rad); -webkit-transform: rotate(0.00rad);" width="243"></span></span></div>
	<br>
	<p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:8pt;text-align:justify">
		<span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;font-weight:700;vertical-align:baseline;white-space:pre-wrap">BƯỚC 3</span><span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap">: Sau khi liên kết ngân hàng xong, chọn chức năng </span><span style="font-size:12pt;font-family:Tahoma;color:rgb(204,0,0);background-color:transparent;font-weight:700;vertical-align:baseline;white-space:pre-wrap">THANH TOÁN</span></p>
	<div style="display:block;text-align:center;margin-right:auto;margin-left:auto">
		<span id="docs-internal-guid-082b68c4-7fff-598d-44b4-3af45528dadf"><span style="font-size: 11pt; font-family: Tahoma; color: rgb(0, 0, 0); background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;"><img height="391" src="https://lh5.googleusercontent.com/AqSgJDGt4oLAiIvNcSAGkyv8_Cdqktw6HJfqjTu46qhTDM_tzVL-ecjQWCaft1Kqb7szuujqcHRPD8_Rdtdx5vgkq7r2Etg1M66gc5c0_C8531hXsRteIHLuEg3rACaQDxYgrtWyEQTZYW1hBQ" style="border: none; transform: rotate(0.00rad); -webkit-transform: rotate(0.00rad);" width="262"></span></span></div>
	<br>
	<p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:8pt;margin-left:4.5pt;text-align:justify">
		<span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap">Sau khi màn hình điện thoại hiện khung </span><span style="font-size:12pt;font-family:Tahoma;color:rgb(153,0,0);background-color:transparent;font-weight:700;vertical-align:baseline;white-space:pre-wrap">QUÉT MÃ QR </span><span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap">bằng camera, hãy điều chỉnh đến khung </span><span style="font-size:12pt;font-family:Tahoma;color:rgb(153,0,0);background-color:transparent;font-weight:700;vertical-align:baseline;white-space:pre-wrap">MÃ QR</span><span style="font-size:12pt;font-family:Tahoma;color:rgb(255,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap"> </span><span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap">của Thiên Long Tình Kiếm bên dưới:</span></p>
	<p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:8pt;text-align:center">
		<span id="docs-internal-guid-d9650db4-7fff-6f69-b02f-27e64f64560a"><span style="font-size: 12pt; font-family: Tahoma; color: rgb(0, 0, 0); background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;"><img src="https://www.upsieutoc.com/images/2019/11/19/QRcode1.png" style="border: none; transform: rotate(0rad); width: 192px; height: 193px;"></span></span></p>
	<div style="display:block;text-align:center;margin-right:auto;margin-left:auto">
		<span id="docs-internal-guid-21e40ee4-7fff-83d7-0585-891585aeac56"><span style="font-size: 12pt; font-family: Tahoma; color: rgb(0, 0, 0); background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;"><img height="432" src="https://lh3.googleusercontent.com/qfvES1kUPuEwcHXi36U0Qra5gcWbgdIyR-y-0wOwyvuevpQcuGy0WZbgLSqsNDNZGcu-CXjSl0Cps99TpgS9S3XkliRol_GPJmWBgjAOwzYkUstewGSowFHN-w6RXJfSg3uJK4Ys" style="border: none; transform: rotate(0.00rad); -webkit-transform: rotate(0.00rad);" width="369"></span></span></div>
	<br>
	<p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:8pt;text-align:center">
		<span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;font-style:italic;vertical-align:baseline;white-space:pre-wrap">Ảnh minh họa quét mã QR Thiên Long Tình Kiếm </span></p>
	<p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:0pt;text-align:justify">
		<span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;font-weight:700;vertical-align:baseline;white-space:pre-wrap">BƯỚC 4</span><span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap">: Nhập số tiền cần nạp và lời nhắn.</span></p>
	<p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:0pt;text-align:justify">
		<font color="#ff0000"><span style="font-size:12pt;font-family:Tahoma;background-color:transparent;font-weight:700;vertical-align:baseline;white-space:pre-wrap">Chú ý:</span><span style="font-size:12pt;font-family:Tahoma;background-color:transparent;vertical-align:baseline;white-space:pre-wrap"> </span></font><span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap">Phần lời nhắn, soạn lời nhắn theo cú pháp sau:</span><span style="font-size:12pt;font-family:Tahoma;color:rgb(153,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap"> </span><span style="font-size:12pt;font-family:Tahoma;color:rgb(255,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap"><b>tên tài khoản, tên server</b> &nbsp;</span><span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap">sau đó</span><span style="font-size:12pt;font-family:Tahoma;color:rgb(255,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap"> </span><span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap">ấn nút <b>Tiếp Tục</b> để xác nhận chuyển tiền.</span></p>
	<div style="display:block;text-align:center;margin-right:auto;margin-left:auto">
		<span id="docs-internal-guid-7b7201d1-7fff-2440-9fa4-3cb96ebc9612"><span style="font-size: 11pt; font-family: Tahoma; color: rgb(0, 0, 0); background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;"><img height="270" src="https://lh5.googleusercontent.com/l3t9VEqmRcc9Pm6DyvZdvm6mvR4CGtawfkzRie6DBSXwI1MI2KdMsDOWnG_SG8SZXwIjBy8ZvNQFHffIkF0vZAzoaD6RR-sfazTsx2ZihclKLOBR2nEzir51DhcJf6LSFqy9F-1n" style="border: none; transform: rotate(0.00rad); -webkit-transform: rotate(0.00rad);" width="272"></span></span></div>
	<br>
	<p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:0pt;text-align:center">
		<span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;font-style:italic;vertical-align:baseline;white-space:pre-wrap">Mẫu lời nhắn: dungnhily, dukiem</span></p>
	<br>
	<p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:0pt;text-align:center">
		<span id="docs-internal-guid-8d0695e3-7fff-f078-5954-15f22a9643a4"><span style="font-size: 12pt; font-family: Tahoma; color: rgb(0, 0, 0); background-color: transparent; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;"><img height="431" src="https://lh6.googleusercontent.com/rQ6sYdkjfbFUI9kEiFIYb7C9Oxo3y9hQGaFzmDw_shanSAAOW57Pa7-l_h67XyN4ayIsoL5u76Q6pki1TsQklewm0FtXBUJ5U42AVOeKhKNLkKg70oELUrxBT0nwSTuprDGvZgNP" style="border: none; transform: rotate(0.00rad); -webkit-transform: rotate(0.00rad);" width="290"></span></span></p>
	<p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:0pt;text-align:center">
		<span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;font-style:italic;vertical-align:baseline;white-space:pre-wrap">Chuyển tiền thành công</span></p>
	<p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:0pt;text-align:center">
		&nbsp;</p>
	<p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:8pt;text-align:justify">
		<span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;font-weight:700;vertical-align:baseline;white-space:pre-wrap">BƯỚC 5</span><span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap">: Sau khi hoàn tất 4 bước trên, vui lòng chờ nhận ĐỒNG được nạp vào tài khoản của bạn.</span><br>
		<span style="font-size:14pt;font-family:Tahoma;color:rgb(255,0,0);background-color:transparent;font-weight:700;vertical-align:baseline;white-space:pre-wrap">Lưu ý: ĐỒNG sẽ được chuyển vào tài khoản của bạn sau 10 phút thanh toán thành công.</span></p>
	<p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:8pt;text-align:justify">
		<span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap">Nếu gặp khó khăn trong quá trình nạp thẻ </span><span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,255);background-color:transparent;vertical-align:baseline;white-space:pre-wrap">ZaloPay</span><span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap">, hãy liên hệ ngay bộ phận hỗ trợ qua fanpage </span><a href="https://www.facebook.com/tinhkiem/"><span style="font-size:12pt;font-family:Tahoma;color:rgb(17,85,204);background-color:transparent;vertical-align:baseline;white-space:pre-wrap">Thiên Long Tình Kiếm</span></a><span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap"> để được trợ giúp. </span></p>
	<p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:8pt;text-align:justify">
		<span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap">Trân Trọng, </span></p>
	<p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:8pt;text-align:justify">
		<span style="font-size:12pt;font-family:Tahoma;color:rgb(0,0,0);background-color:transparent;vertical-align:baseline;white-space:pre-wrap"><b>BQT Thiên Long Tình Kiếm</b></span></p>
	<p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:8pt;text-align:justify">
		<span style="font-size:11pt;font-family:Tahoma;color:rgb(0,0,0);vertical-align:baseline;white-space:pre-wrap">------------------------------------------------------</span><br>
		<span style="font-size:11pt;font-family:Tahoma;color:rgb(0,0,0);vertical-align:baseline;white-space:pre-wrap">TLBB Tình Kiếm - TLBB Private Server đông vui nhất Việt Nam</span><br>
		<span style="font-size:11pt;font-family:Tahoma;color:rgb(0,0,0);vertical-align:baseline;white-space:pre-wrap">Trang chủ</span><a href="http://game4you.us/"><span style="font-size:11pt;font-family:Tahoma;color:rgb(0,0,0);vertical-align:baseline;white-space:pre-wrap"> </span><span style="font-size:11pt;font-family:Tahoma;color:rgb(17,85,204);vertical-align:baseline;white-space:pre-wrap">http://game4you.us/</span></a><span style="font-size:11pt;font-family:Tahoma;color:rgb(17,85,204);vertical-align:baseline;white-space:pre-wrap"> </span><span style="font-size:11pt;font-family:Tahoma;color:rgb(0,0,0);vertical-align:baseline;white-space:pre-wrap">-</span><a href="http://tinhkiem.us/"><span style="font-size:11pt;font-family:Tahoma;color:rgb(17,85,204);vertical-align:baseline;white-space:pre-wrap"> http://tinhkiem.us</span></a><br>
		<span style="font-size:11pt;font-family:Tahoma;color:rgb(0,0,0);vertical-align:baseline;white-space:pre-wrap">Download</span><a href="http://game4you.us/download/"><span style="font-size:11pt;font-family:Tahoma;color:rgb(0,0,0);vertical-align:baseline;white-space:pre-wrap"> </span><span style="font-size:11pt;font-family:Tahoma;color:rgb(17,85,204);vertical-align:baseline;white-space:pre-wrap">http://game4you.us/download/</span></a><br>
		<span style="font-size:11pt;font-family:Tahoma;color:rgb(0,0,0);vertical-align:baseline;white-space:pre-wrap">Đăng ký</span></p>
	<p dir="ltr" style="line-height:1.7999999999999998;margin-top:0pt;margin-bottom:8pt;text-align:justify">
		<a href="http://id.game4you.us/manage/#Register"><span style="font-size:11pt;font-family:Tahoma;color:rgb(17,85,204);vertical-align:baseline;white-space:pre-wrap">http://id.game4you.us/manage/#Register</span></a></p>
</div>
<p>
	&nbsp;</p>


            </div>
@endsection